### ISSUE TITLE
An useless exception when a search query has syntax errors

### ISSUE THREAD

**Issue by UvaK** [karmi/retire#109]
As example:

``` ruby
> MyModel.search('Text with syntax errors, as example exclamation mark in the end!')

NoMethodError: undefined method `results' for false:FalseClass
    from /home/cosinus/.rvm/gems/ruby-1.8.7-p334@freiminuten-3.0/gems/tire-0.3.3/lib/tire/model/search.rb:94:in `search'
    from /home/cosinus/.rvm/gems/ruby-1.8.7-p334@freiminuten-3.0/gems/tire-0.3.3/lib/tire/model/search.rb:256:in `__send__'
    from /home/cosinus/.rvm/gems/ruby-1.8.7-p334@freiminuten-3.0/gems/tire-0.3.3/lib/tire/model/search.rb:256:in `search'
    from (irb):60
```

Better and more correct to return nil or raise special exception (as example SearchFailedError). But even nil will be nice.

**Comment by karmi** [comment]
Hi, yeah, this is quite stupid. Will look into that. It's another unfortunate impact of the "HTTP agnostic" stuff.

**Comment by ramontayag** [comment]
Hey @karmi,

I upgraded to `0.3.8` but I still get an error like this:

```
> Album.search 'hey!'
[REQUEST FAILED] curl -X GET "http://localhost:9200/development/album/_search?pretty=true" -d '{"query":{"query_string":{"query":"hey!"}}}'
Tire::Search::SearchRequestFailed: Tire::Search::SearchRequestFailed
    from /Users/dev/.rvm/gems/ree-1.8.7-2011.03@mtrax2/gems/tire-0.3.8/lib/tire/search.rb:74:in `perform'
    from /Users/dev/.rvm/gems/ree-1.8.7-2011.03@mtrax2/gems/tire-0.3.8/lib/tire/model/search.rb:97:in `search'
    from /Users/dev/.rvm/gems/ree-1.8.7-2011.03@mtrax2/gems/tire-0.3.8/lib/tire/model/search.rb:264:in `__send__'
    from /Users/dev/.rvm/gems/ree-1.8.7-2011.03@mtrax2/gems/tire-0.3.8/lib/tire/model/search.rb:264:in `search'
    from (irb):1
```

**Comment by ramontayag** [comment]
I upgraded to `0.3.12` and get this error when searching for 'hey!'

```
500 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[8nXMyBO_QQ-umfZPyRgnrg][development][3]: SearchParseException[[development][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"hey!\"}}}]]]; nested: QueryParsingException[[development] Failed to parse query [hey!]]; nested: ParseException[Cannot parse 'hey!': Encountered \"<EOF>\" at line 1, column 4.\nWas expecting one of:\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    \"*\" ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 4.\nWas expecting one of:\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    \"*\" ...\n    ]; }{[8nXMyBO_QQ-umfZPyRgnrg][development][1]: SearchParseException[[development][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"hey!\"}}}]]]; nested: QueryParsingException[[development] Failed to parse query [hey!]]; nested: ParseException[Cannot parse 'hey!': Encountered \"<EOF>\" at line 1, column 4.\nWas expecting one of:\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    \"*\" ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 4.\nWas expecting one of:\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    \"*\" ...\n    ]; }]","status":500}
```

**Comment by karmi** [comment]
@ramontayag Hi, the `!` in "hey!" breaks the Lucene syntax parser -- either escape it or use the `text` query /http://www.elasticsearch.org/guide/reference/query-dsl/text-query.html/
