### ISSUE TITLE
illegal ObjectId format: Lorem

### ISSUE THREAD

**Issue by krainboltgreene** [karmi/retire#213]
``` ruby
# literature.rb
class Literature
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Tire::Model::Search
  include Tire::Model::Callbacks

  field :title
  field :body
  field :rating, type: Integer, default: 0

  alias_method :to_indexed_json, :to_json
end
class Story < Literature
end
```

``` ruby
# stories_controller.rb

class Literature::StoriesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
    if params[:query]
      @stories = Story.search params[:query], load: true  # => illegal ObjectId format: Lorem
    else
      @stories = Story.all
    end
  end

  def show
  end

  def search
  end
end
```

```
http://localhost:3000/literature/stories?utf8=%E2%9C%93&query=Lorem
```

Any thoughts?

*Edit: Oh, and gemfile:

``` ruby
source :rubygems

gem 'rails', '~> 3.2'
gem 'mongoid', '~> 2.3'
gem 'bson_ext', '~> 1.5'
gem 'bcrypt-ruby', '~> 3.0', require: 'bcrypt'
gem 'sorcery', '~> 0.7'
gem 'draper', '~> 0.9'
gem 'thin', '~> 1.3'
gem 'slim-rails', '~> 0.2'
gem 'sass-rails', '~> 3.1'
gem 'coffee-rails', '~> 3.1'
gem 'jquery-rails', '~> 2.0'
gem 'redcarpet', '~> 2.0'
gem 'tire', '~> 0.3'

group :development, :test do
  gem 'rspec-rails', '~> 2.7'
  gem 'fabrication', '~> 1.2'
  gem 'forgery', '~> 0.5'
end

group :development do
  gem 'heroku', '~> 2.16', require: false
  gem 'awesome_print', '~> 1.0'
  gem 'rails_best_practices', '~> 1.7', require: false
  gem 'guard', '~> 1.0', require: false
  gem 'guard-spork', '~> 0.4', require: false
  gem 'guard-rspec', '~> 0.5', require: false
end

group :test do
  gem 'spork', '~> 0.8'
  gem 'cucumber', '~> 1.1'
  gem 'capybara', '~> 1.1'
  gem 'database_cleaner', '~> 0.7'
  gem 'shoulda-matchers', '~> 1.0'
  gem 'mongoid-rspec', '~> 1.4'
end

group :assets do
  gem 'uglifier', '~> 1.2'
end

```

*Edit 2: Stacktrace

``` bash
bson (1.5.2) lib/bson/types/object_id.rb:126:in `from_string'
mongoid (2.4.1) lib/mongoid/fields/internal/object_id.rb:38:in `serialize'
mongoid (2.4.1) lib/mongoid/criterion/optional.rb:97:in `for_ids'
mongoid (2.4.1) lib/mongoid/criteria.rb:309:in `search'
mongoid (2.4.1) lib/mongoid/finders.rb:15:in `search'
app/controllers/literature/stories_controller.rb:16:in `index'
actionpack (3.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.0) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.0) lib/active_support/callbacks.rb:436:in `_run__3746020949630808022__process_action__3532531638300048989__callbacks'
activesupport (3.2.0) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.0) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.0) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.0) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.0) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.0) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.0) lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
actionpack (3.2.0) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.0) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.0) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.0) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.0) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.0) lib/action_dispatch/routing/route_set.rb:66:in `call'
actionpack (3.2.0) lib/action_dispatch/routing/route_set.rb:66:in `dispatch'
actionpack (3.2.0) lib/action_dispatch/routing/route_set.rb:30:in `call'
journey (1.0.0) lib/journey/router.rb:60:in `block in call'
journey (1.0.0) lib/journey/router.rb:48:in `each'
journey (1.0.0) lib/journey/router.rb:48:in `call'
actionpack (3.2.0) lib/action_dispatch/routing/route_set.rb:570:in `call'
mongoid (2.4.1) lib/rack/mongoid/middleware/identity_map.rb:33:in `block in call'
mongoid (2.4.1) lib/mongoid.rb:132:in `unit_of_work'
mongoid (2.4.1) lib/rack/mongoid/middleware/identity_map.rb:33:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.0) lib/rack/etag.rb:23:in `call'
rack (1.4.0) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.0) lib/rack/session/abstract/id.rb:205:in `context'
rack (1.4.0) lib/rack/session/abstract/id.rb:200:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/cookies.rb:338:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.0) lib/active_support/callbacks.rb:405:in `_run__1402955422462027413__call__4236371761903959113__callbacks'
activesupport (3.2.0) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.0) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.0) lib/rails/rack/logger.rb:26:in `call_app'
railties (3.2.0) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.0) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.0) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.0) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.0) lib/rack/lock.rb:15:in `call'
actionpack (3.2.0) lib/action_dispatch/middleware/static.rb:53:in `call'
railties (3.2.0) lib/rails/engine.rb:479:in `call'
railties (3.2.0) lib/rails/application.rb:220:in `call'
rack (1.4.0) lib/rack/content_length.rb:14:in `call'
railties (3.2.0) lib/rails/rack/log_tailer.rb:14:in `call'
thin (1.3.1) lib/thin/connection.rb:80:in `block in pre_process'
thin (1.3.1) lib/thin/connection.rb:78:in `catch'
thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:53:in `process'
thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
thin (1.3.1) lib/thin/server.rb:159:in `start'
rack (1.4.0) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.0) lib/rack/server.rb:265:in `start'
railties (3.2.0) lib/rails/commands/server.rb:70:in `start'
railties (3.2.0) lib/rails/commands.rb:55:in `block in <top (required)>'
railties (3.2.0) lib/rails/commands.rb:50:in `tap'
railties (3.2.0) lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

**Comment by karmi** [comment]
> Any thoughts?

Yes, I don't think `alias_method :to_indexed_json, :to_json` will work for Mongoid.

Also, I don't know what's the issue you're reporting. `bson (1.5.2) lib/bson/types/object_id.rb:126:in`from_string'`?`illegal ObjectId format: Lorem`?

**Comment by krainboltgreene** [comment]
> Yes, I don't think `alias_method :to_indexed_json, :to_json` will work for Mongoid.

Your code in the readme:

``` ruby
def to_indexed_json
  self.to_json
end
```

is the same as

``` ruby
alias_method :to_indexed_json, :to_json
```

> Also, I don't know what's the issue you're reporting.

And I'm reporting that `Story.search "Lorem"` results in an exception that none of your documentation seems to cover.

**Comment by krainboltgreene** [comment]
For what it's worth, if I call `Story.tire.search params[:query], load: true` I get a `@response` object, with a lot of nested hashes.

**Comment by krainboltgreene** [comment]
If I attempt to use `Store.tire.search` I get this error:

```
Document not found for class Story with id(s) 4f1c67c1a53b22f41b000002, 4f1c67c1a53b22f41b000007, 4f1c6832a53b22f4d5000004, 4f1c6832a53b22f4d5000009, 4f1c6832a53b22f4d500000a, 4f1c683fa53b22f506000005, 4f1c6df9a53b22f93d000001, 4f1c6df9a53b22f93d000006, 4f1c7109a53b22fc97000004, 4f1c7109a53b22fc97000009.
```

I wonder if my `es` instance has old objects that don't match objects in my MongoDB?

**Comment by krainboltgreene** [comment]
Ok, I've fixed the issue. Here's what I had to do, from the beginning:
1. Change `Story.search` to `Story.tire.search`
2. Drop the ES index with `Story.tire.index.delete`
3. Reseed the database: `rake db:reseed`

And now it works. I get full on Mongoid objects.

**Comment by karmi** [comment]
Awesome.
