### ISSUE TITLE
Matches method pollutes similar model method

### ISSUE THREAD

**Issue by brandonhilkert** [karmi/retire#280]
We're using Mongomapper and are attempting to index user documents. We have a key on our document called "matches", which is an array. When we go to index a user document, we get this error:

`````` Ruby
class User
  key :matches,                   Array
  ...
end


````Ruby
irb(main):001:0> ap User.brandon
NoMethodError: undefined method `[]' for nil:NilClass
    from /Users/bhilkert/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/tire-0.3.12/lib/tire/model/search.rb:165:in `matches'
    from /Users/bhilkert/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/tire-0.3.12/lib/tire/model/search.rb:274:in `matches'
``````

**Comment by karmi** [comment]
Try to `include` _Tire_ after you define all your properties. It should not over-ride already existing methods.

**Comment by brandonhilkert** [comment]
Worked perfect. Thanks!

**Comment by karmi** [comment]
Great .)
