### ISSUE TITLE
Bonsai.io/Heroku and Tire just work locally but not on Heroku

### ISSUE THREAD

**Issue by lgs** [karmi/retire#365]
Hi, I'd need some help with that, until now evrything works fine on my local machine but not on heroku. I get nothing in response to the same search.

This is my config/initializers/bonsai.rb but at first, I cannot have any log back form rails logger ( both in local or on heroku):

<pre>
Tire.configure { logger 'elasticsearch.log', :level => 'debug' }
if ENV['BONSAI_INDEX_URL']
  Tire.configure do
    url "http://index.bonsai.io"
  end
  BONSAI_INDEX_NAME = ENV['BONSAI_INDEX_URL'][/[^\/]+$/]
else
  app_name = Rails.application.class.parent_name.underscore.dasherize
  app_env = Rails.env
  BONSAI_INDEX_NAME = "#{app_name}-#{app_env}"
end
</pre>

Second I run `rake environment tire:import` like the following:

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ heroku run:detached rake environment tire:import CLASS=Event FORCE=true
Running rake environment tire:import CLASS=Event FORCE=true... up, run.2
Use 'heroku logs -p run.2' to view the log output.
lsoave@ubuntu:~/rails/github/gitwatcher$
</pre>

... here it is a gist of what heroku logged in responce: https://gist.github.com/2864870

Third, trying curl I get the following, but in my browser ... nothing :

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ curl  http://index.bonsai.io/asjgayz4s827lhj8u3r7/category?pretty=true -d '{"name": "Ruby Web Frameworks"}'
{
 "ok" : true,
 "_index" : "asjgayz4s827lhj8u3r7-1338416002",
 "_type" : "category",
 "_id" : "Clb9uXX5Rw6SR7qOHPGrlA",
 "_version" : 1
}lsoave@ubuntu:~/rails/github/gitwatcher$

lsoave@ubuntu:~/rails/github/gitwatcher$ curl  http://index.bonsai.io/asjgayz4s827lhj8u3r7/category/Clb9uXX5Rw6SR7qOHPGrlA?pretty=true
{
 "_index" : "asjgayz4s827lhj8u3r7-1338416002",
 "_type" : "category",
 "_id" : "Clb9uXX5Rw6SR7qOHPGrlA",
 "_version" : 1,
 "exists" : true, "_source" : {"name": "Ruby Web Frameworks"}
}lsoave@ubuntu:~/rails/github/gitwatcher$
</pre>

**Comment by lgs** [comment]
WTF, the `rake environment tire:import` was on the wrong model ( my fault sorry ), now it's ok (updated the gist). 

Anyway, now  i get a 500 Internal Server Error back when I do the same matching search.  All what heroku logs,  is the following :

<pre>
2012-06-03T21:52:41+00:00 heroku[router]: GET gitwatcher.com/categories dyno=web.1 queue=0 wait=0ms service=10751ms status=200 bytes=61424
2012-06-03T21:52:41+00:00 heroku[nginx]: 93.34.112.205 - - [03/Jun/2012:21:52:41 +0000] "GET /categories HTTP/1.1" 200 12238 "http://gitwatcher.com/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0" gitwatcher.com
2012-06-03T21:52:41+00:00 heroku[router]: GET gitwatcher.com/assets/application-4083955e163027c3e232b6edc9cf4dd1.js dyno=web.1 queue=0 wait=0ms service=166ms status=200 bytes=204559
2012-06-03T21:52:41+00:00 heroku[router]: GET gitwatcher.com/assets/application-02cfedf8524ef0a3da8856f66a3c61df.css dyno=web.1 queue=0 wait=0ms service=152ms status=200 bytes=178764
2012-06-03T21:52:41+00:00 heroku[nginx]: 93.34.112.205 - - [03/Jun/2012:21:52:41 +0000] "GET /assets/application-02cfedf8524ef0a3da8856f66a3c61df.css HTTP/1.1" 200 21013 "http://gitwatcher.com/categories" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0" gitwatcher.com
2012-06-03T21:52:41+00:00 heroku[nginx]: 93.34.112.205 - - [03/Jun/2012:21:52:41 +0000] "GET /assets/application-4083955e163027c3e232b6edc9cf4dd1.js HTTP/1.1" 200 64853 "http://gitwatcher.com/categories" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0" gitwatcher.com
2012-06-03T21:52:46+00:00 app[web.1]: MONGODB (235ms) heroku_app1707530['users'].find({:_id=>BSON::ObjectId('4f82c1127c0c220001000001')}).limit(-1).sort([[:_id, :asc]])
2012-06-03T21:52:46+00:00 heroku[router]: GET gitwatcher.com/categories?utf8=%E2%9C%93&query=Asynchronous+Web+Frameworks dyno=web.1 queue=0 wait=0ms service=358ms status=500 bytes=728
2012-06-03T21:52:46+00:00 heroku[nginx]: 93.34.112.205 - - [03/Jun/2012:21:52:46 +0000] "GET /categories?utf8=%E2%9C%93&query=Asynchronous+Web+Frameworks HTTP/1.1" 500 728 "http://gitwatcher.com/categories" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0" gitwatcher.com
</pre>

**Comment by nz** [comment]
@lgs — your Bonsai index URL is intended to be private, like a database password. you may want to remove and re-add the addon at some point to get a new private URL.

**Comment by nz** [comment]
That aside, I'm having a hard time seeing what the issue may be here, or whether it's even coming from the bonsai.io side… If anyone can help me duplicate the issue I'd appreciate it.

@lgs, please email me at support@onemorecloud.com if you can create a request (or series of requests) with curl that duplicate the issue.

**Comment by lgs** [comment]
Ok, thanks for advising about the index URL, I already regenerated.  I also update tire (~> 0.4.2) but without any success. On my local PC it works, on Heroku fails silently. Is there a better way of logging elastic/bonsai/heroku ?

**Comment by lgs** [comment]
Setting up `logger $stdout, :level => 'debug'` into `Tire.configure` finally heroku can log something while it's failing search :

<pre>
2012-06-04T21:36:26+00:00 heroku[router]: GET gitwatcher.com/categories?utf8=%E2%9C%93&query=Asynchronous+Web+Frameworks dyno=web.1 queue=0 wait=0ms service=32ms status=500 bytes=728
2012-06-04T21:36:26+00:00 heroku[nginx]: 93.34.212.216 - - [04/Jun/2012:21:36:26 +0000] "GET /categories?utf8=%E2%9C%93&query=Asynchronous+Web+Frameworks HTTP/1.1" 500 728 "http://gitwatcher.com/categories" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0" gitwatcher.com
2012-06-04T21:36:26+00:00 app[web.1]: # 2012-06-04 21:36:26:387 [_search] (["123456789"])
2012-06-04T21:36:26+00:00 app[web.1]: #
2012-06-04T21:36:26+00:00 app[web.1]: curl -X GET "http://index.bonsai.io/123456789/category/_search?load=true&pretty=true" -d '{"query":{"query_string":{"query":"Asynchronous Web Frameworks"}}}'
2012-06-04T21:36:26+00:00 app[web.1]:
2012-06-04T21:36:26+00:00 app[web.1]: # 2012-06-04 21:36:26:387 [200] (1 msec)
2012-06-04T21:36:26+00:00 app[web.1]:
</pre>


Then running curl, there something strange:  the retourning object, seems to be duplicated ( the search was on "Ruby Web Frameworks" category, which appear two times with different _id ) :

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ curl -X GET "http://index.bonsai.io/123456789/category/_search?load=true&pretty=true" -d '{"query":{"query_string":{"query":"Ruby Web Frameworks"}}}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 0.78854096,
    "hits" : [ {
      "_index" : "123456789-xxxxxx",
      "_type" : "category",
      "_id" : "LAm-hNglS5mbrMzDlVVHCQ",
      "_score" : 0.78854096, "_source" : {"name": "Ruby Web Frameworks"}
    }, {
      "_index" : "123456789-xxxxxx",
      "_type" : "category",
      "_id" : "h8Gm7rPbRGihbn0R0Gj9lg",
      "_score" : 0.78854096, "_source" : {"name": "Ruby Web Frameworks"}
    } ]
  }
lsoave@ubuntu:~/rails/github/gitwatcher$
</pre>


moreover I get a Progstr Logger error alert via Heroku add-on which say

<pre>
BSON::InvalidObjectId (illegal ObjectId format: LAm-hNglS5mbrMzDlVVHCQ):
 app/controllers/categories_controller.rb:25:in `index'
</pre>


and the offending line is the following :

<pre>
 24     @categories.each do |category|
 25             @competitors["#{category.path}"] = Category.find_competitors_by_tags(category.tags_array)
 26     end
</pre>

**Comment by nz** [comment]
Thanks for the extra details, @lgs. I suspect the earlier error was from the process failing to write out its log messages. As far as your search results, they seem normal to me. Those are just two different documents in your index, as indicated by the unique document `_id` fields. Likely they weren't indexed with an ID?

Not sure I see an error here yet. Have you tried to reindex your data since changing the logger?

**Comment by lgs** [comment]
Re-indexing clomplete succesfully ( see https://gist.github.com/2871366 ) but  I get the same error as before.

**Comment by nz** [comment]
I'll have to defer to the expertise of @karmi or someone else on the rest…

**Comment by lgs** [comment]
By what I can understand, there's nothing wrong with bonsai.io, infact all the search are logged correctly, both if they match or not :

<pre>
2012-06-06T18:36:43+00:00 app[web.1]: MONGODB (178ms) heroku_app1707530['users'].find({:_id=>BSON::ObjectId('4f82c1127c0c220001000001')}).limit(-1).sort([[:_id, :asc]])
2012-06-06T18:36:43+00:00 app[web.1]: # 2012-06-06 18:36:42:960 [_search] (["f-a-k-e-i-n-d-e-x"])
2012-06-06T18:36:43+00:00 app[web.1]: #
2012-06-06T18:36:43+00:00 app[web.1]: curl -X GET "http://index.bonsai.io/f-a-k-e-i-n-d-e-x/category/_search?load=true&pretty=true" -d '{"query":{"query_string":{"query":"Asynchronous Web Frameworks"}}}'
2012-06-06T18:36:43+00:00 app[web.1]: 
2012-06-06T18:36:43+00:00 app[web.1]: # 2012-06-06 18:36:42:961 [200] (0 msec)
2012-06-06T18:36:43+00:00 app[web.1]: #
2012-06-06T18:36:43+00:00 app[web.1]: # {"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":2,"max_score":0.26039517,"hits":[{"_index":"f-a-k-e-i-n-d-e-x-111222","_type":"category","_id":"LAm-hNglS5mbrMzDlVVHCQ","_score":0.26039517,"_source":{"name":"Ruby Web Frameworks"}},{"_index":"sb0cqngrfo2rp1hvw0kl-1338766652","_type":"category","_id":"h8Gm7rPbRGihbn0R0Gj9lg","_score":0.26039517,"_source":{"name":"Ruby Web Frameworks"}}]}}
2012-06-06T18:36:43+00:00 app[web.1]: 
2012-06-06T18:40:08+00:00 heroku[router]: GET gitwatcher.herokuapp.com/ dyno=web.1 queue=0 wait=0ms service=8ms status=301 bytes=87
2012-06-06T18:40:08+00:00 heroku[router]: GET gitwatcher.com/ dyno=web.1 queue=0 wait=0ms service=13ms status=200 bytes=8309
2012-06-06T18:40:08+00:00 heroku[nginx]: 184.73.150.97 - - [06/Jun/2012:18:40:08 +0000] "GET / HTTP/1.1" 200 3284 "-" "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/533.3 (KHTML, like Gecko) stillalive-webkit-bot/0.0.17 Safari/533.3" gitwatcher.com
</pre>


... while something goes wrong during the controller call, which produce a `BSON::InvalidObjectId (illegal ObjectId)` format error:

<pre>
BSON::InvalidObjectId (illegal ObjectId format: LAm-hNglS5mbrMzDlVVHCQ):
  app/controllers/categories_controller.rb:25:in `index'
</pre>


Now please note that my controller is never bitten, infact I put a lot of Rails.logger.info to debug the issue, but they are never displaied on `heroku logs --tail`. Here it is a snippet of the controller to show what I mean:

<pre>
      @categories = Category.search(params[:query], load: true)
      Rails.logger.info "\r\n" + "#{Time.now} " + "@categories = Category.search(params[:query], load: true)" + "\r\n"
      Rails.logger.info "\r\n" + "#{Time.now} " + "@categories #{@categories}" + "\r\n"
      Rails.logger.info "\r\n" + "#{Time.now} " + "@categories.class #{@categories.class}" + "\r\n"
      #Rails.logger.info "\r\n" + "#{Time.now} " + "@categories.results #{@categories.results}" + "\r\n"
      Rails.logger.info "\r\n" + "#{Time.now} " + "@categories.inspect #{@categories.inspect}" + "\r\n"

      #@categories.results.each do |category|
      @categories.each do |category|
        Rails.logger.info "\r\n" + "#{Time.now} " + "Start @categories.each" + "\r\n"
        #Rails.logger.info "\r\n" + "#{Time.now} " + "Start @categories.results.each (if params[:query])" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "category #{category}" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "category.name #{category.name}" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "category.path = #{category.path}" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "category.tags_array #{category.tags_array}" + "\r\n"
        @competitors["#{category.path}"] = Category.find_competitors_by_tags(category.tags_array)
        Rails.logger.info "\r\n" + "#{Time.now} " + "@competitors = #{@competitors}" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "@competitors.class = #{@competitors.class}" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "@competitors[#{category.path}] = #{@competitors["#{category.path}"]}" + "\r\n"
        Rails.logger.info "\r\n" + "#{Time.now} " + "End @categories.results.each (if params[:query])" + "\r\n"
      end
</pre>


Please don't forget that locally on my linux machine, this code works fine. May be is something related to mongodb version of MongoLab/Heroku add-on provider ? 

What do you say ?

<pre>
> db.version()
2.0.4
> 
</pre>


<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ egrep "bson|mongo" Gemfile.lock
  remote: https://github.com/mongoid/mongoid.git
    mongoid (3.0.0)
      mongo (~> 1.3)
    bson (1.6.1)
    bson_ext (1.6.1)
      bson (~> 1.6.1)
    mongo (1.6.1)
      bson (~> 1.6.1)
    mongoid_taggable_with_context (0.8.1)
      mongoid (>= 2.0.0)
      mongoid (>= 2.4.3)
  bson
  bson_ext
  mongoid!
  mongoid_taggable_with_context (= 0.8.1)
lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>

**Comment by karmi** [comment]
@lgs The `BSON::InvalidObjectId` is usually coming from incorrectly serializing a Mongoid model instance to JSON -- see the Readme, you have to manually override `to_indexed_json` for Mongoid.

I'm wondering about the logger incompatibility, Tire's `logger` method should definitely accept a `Rails.logger` instance....

**Comment by lgs** [comment]
Thanks  karmi, 
I already had `to_indexed_json` in my Category MongoID method like following:

<pre>
    ...
      def to_indexed_json
        self.as_json
      end
   ...
</pre>


about logger, ... at the end of the day I currently have logger setted like following:
config/initializers/bonsai.rb

<pre>
Tire.configure { logger $stdout, :level => 'debug' }

if ENV['BONSAI_INDEX_URL']
  Tire.configure do
    url "http://index.bonsai.io"
  end
  BONSAI_INDEX_NAME = ENV['BONSAI_INDEX_URL'][/[^\/]+$/]
else
  app_name = Rails.application.class.parent_name.underscore.dasherize
  app_env = Rails.env
  BONSAI_INDEX_NAME = "#{app_name}-#{app_env}"
end
</pre>

**Comment by lgs** [comment]
OK, now is better :

<pre>    
    DEFINETLY WORKS BY:
      1)  dropping out `to_indexed_json` from Category MongoID model ( at the opposit of README indication )
      2)  removing and re-adding Bonsai.io Heroku add-on
      3)  reindexing ElasticSearch by running `heroku run:detached rake environment tire:import CLASS='Category'`
</pre>


... infact, if you just run `rake environment tire:import CLASS='Category' FORCE=true` it doesn't work on Heroku/Bonsai.io, becuse of Bonsai authorized operation :

<pre>
  2012-06-11T20:39:30+00:00 app[run.1]: curl -X DELETE http://index.bonsai.io/my-fake-index-11223344
  2012-06-11T20:39:30+00:00 app[run.1]: # 2012-06-11 20:39:30:749 [401]
  2012-06-11T20:39:30+00:00 app[run.1]: #
  2012-06-11T20:39:30+00:00 app[run.1]: # "{\"error\": \"Not authorized: Some endpoints are admin-only, ask support@onemorecloud.com.\"}\n"
</pre>


than if you want to reset/reindex your eventually dirty data, the only way is dropping the Bonsai add-on and recreate:

<pre>
  heroku addons:remove bonsai:test
  heroku addons:add bonsai:test
</pre>


That saied, I really had a dirty data indicated by :

<pre>
  BSON::InvalidObjectId (illegal ObjectId format: LAm-hNglS5mbrMzDlVVHCQ):
  app/controllers/categories_controller.rb:25:in `index'
</pre>


 If you'll need the full gem stack to compare with other cases, here it is: https://gist.github.com/2912881
