### ISSUE TITLE
After upgrade to Rails 3.2.9 and tire 0.5.1 indexing is not working

### ISSUE THREAD

**Issue by andywenk** [karmi/retire#528]
after the upgrade mentioned in the subject of this post, I get the following error:

```
bundle exec rake environment tire:import CLASS='PrinterCartridge' FORCE=true

[IMPORT] Deleting index 'printer_cartridges'
[IMPORT] Creating index 'printer_cartridges' with mapping:
{"printer_cartridge":{"properties":{"id":{"index":{"ruby_class":"Symbol","s":"not_analyzed"},"type":"string"},"manufacturer_name":{"type":"string","analyzer":"snowball","filter":["lowercase"],"boost":700},"cartridge_name":{"type":"string","analyzer":"snowball","filter":["lowercase"],"boost":600},"printer_name":{"type":"string","analyzer":"snowball","filter":["lowercase"],"boost":400}}}}
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":"MapperParsingException[mapping [printer_cartridge]]; nested: MapperParsingException[Wrong value for index [{s=not_analyzed, ruby_class=_symbol}] for field [id]]; ","status":400}
```

The elasticsearch stacktrace is as follows:

```
[2012-11-23 22:22:05,756][INFO ][discovery                ] [Blazing Skull] elasticsearch_andwen/8N83gh08QgKEyvCxRs5V-A
[2012-11-23 22:22:05,782][INFO ][http                     ] [Blazing Skull] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
[2012-11-23 22:22:05,782][INFO ][node                     ] [Blazing Skull] {0.19.9}[21173]: started
[2012-11-23 22:22:06,784][INFO ][gateway                  ] [Blazing Skull] recovered [3] indices into cluster_state
[2012-11-23 22:23:04,577][INFO ][cluster.metadata         ] [Blazing Skull] [printer_cartridges] deleting index
[2012-11-23 22:23:04,826][WARN ][cluster.metadata         ] [Blazing Skull] [printer_cartridges] failed to create
org.elasticsearch.index.mapper.MapperParsingException: mapping [printer_cartridge]
  at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:262)
  at org.elasticsearch.cluster.service.InternalClusterService$2.run(InternalClusterService.java:211)
  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
  at java.lang.Thread.run(Thread.java:680)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Wrong value for index [{s=not_analyzed, ruby_class=_symbol}] for field [id]
  at org.elasticsearch.index.mapper.core.TypeParsers.parseIndex(TypeParsers.java:128)
  at org.elasticsearch.index.mapper.core.TypeParsers.parseField(TypeParsers.java:64)
  at org.elasticsearch.index.mapper.core.StringFieldMapper$TypeParser.parse(StringFieldMapper.java:124)
  at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:261)
  at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:217)
  at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:161)
  at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:364)
  at org.elasticsearch.index.mapper.MapperService.add(MapperService.java:186)
  at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:259)
  ... 4 more
```

This is the mapping I am using:

```
include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :id, :index => :not_analyzed
    indexes :manufacturer_name, :type => 'string', :analyzer => 'snowball', :filter => ['lowercase'], :boost => 700
    indexes :cartridge_name, :type => 'string', :analyzer => 'snowball', :filter => ['lowercase'], :boost => 600
    indexes :printer_name, :type => 'string', :analyzer => 'snowball', :filter => ['lowercase'], :boost => 400
  end
```

Any idea what went wrong? Thanks a lot in advance ... tire is awesome ;-)

**Comment by andywenk** [comment]
I just found out the following. When trying to set a type for id, like

```
indexes :id, :type => 'integer', :index => :not_analyzed
```

or

```
indexes :id, :type => 'string', :index => :not_analyzed
```

the error is the same. But, when completely removing the line, it works. Did anything change in the API? I could not find it ...

**Comment by ike-bloomfire** [comment]
try :index => 'not_analyzed' instead of :not_analyzed

**Comment by karmi** [comment]
@andywenk Sorry for the delay. I think this depends on the JSON library you use, especially `oj` is quite restrictive what it allows. If you set the logging with `Tire.configure { logger STDERR }`, I think you'll see the incorrect value in the mapping (`{s=not_analyzed, ruby_class=_symbol}`).

As suggested, using `String` instead of `Symbol` should fix it.

**Comment by andywenk** [comment]
Hi @ike-bloomfire and @karmi,

thanks a lot for the hint. That worked for me.

Cheers

Andy

**Comment by karmi** [comment]
@andywenk So, closing?

**Comment by andywenk** [comment]
sorry ... sure ... I close it now.

Thanks !

**Comment by karmi** [comment]
No worries, thanks!
