### ISSUE TITLE
Parses responses as file

### ISSUE THREAD

**Issue by riniculous** [karmi/retire#556]
This is for a project that was previously working just fine. I am setting up a new dev machine and found the problem. Another dev also has the problem on an existing setup.
elastic search is install correctly, i can curl it and hit it in browser. Tire appears to be parsing the responses as a file that it can not find. See stack trace below. To be noted i'm using rbenv, where in the past i have been using rvm

```
cannot load such file -- {"ok":true,"_index":"development_users","_type":"user","_id":"1","_version":1}
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `block in load'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/tire-3a9a69041510/lib/tire/index.rb:379:in `logged'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/tire-3a9a69041510/lib/tire/index.rb:90:in `store'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/tire-3a9a69041510/lib/tire/model/search.rb:148:in `block in update_index'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:403:in `_run__2056480869826087306__update_elasticsearch_index__669216497786388976__callbacks'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_update_elasticsearch_index_callbacks'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/tire-3a9a69041510/lib/tire/model/search.rb:144:in `update_index'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/tire-3a9a69041510/lib/tire/model/callbacks.rb:21:in `block in included'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:438:in `_run__2056480869826087306__save__669216497786388976__callbacks'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:264:in `create_or_update'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/persistence.rb:104:in `save!'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/validations.rb:56:in `save!'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/transactions.rb:264:in `block in save!'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/transactions.rb:208:in `transaction'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.5.4.33/lib/new_relic/agent/method_tracer.rb:493:in `block in transaction_with_trace_ActiveRecord_self_name_transaction'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.5.4.33/lib/new_relic/agent/method_tracer.rb:242:in `trace_execution_scoped'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.5.4.33/lib/new_relic/agent/method_tracer.rb:488:in `transaction_with_trace_ActiveRecord_self_name_transaction'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/transactions.rb:264:in `save!'
```

Any response is parsed this way

```
User.tire.index.create(:mappings => User.tire.mapping_to_hash, :settings => User.tire.settings)
LoadError: cannot load such file -- {"error":"IndexAlreadyExistsException[[development_users] Already exists]","status":400}
from /Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
[2] pry(main)> User.tire.index.delete
LoadError: cannot load such file -- {"ok":true,"acknowledged":true}
from /Users/nic/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
```

**Comment by riniculous** [comment]
Sorry it was a miss match on multi_json gem. Mine was older. You might want to set a requirement for the newer version of tire to require the newer multi-json

**Comment by karmi** [comment]
@riniculous Yes, this is related to the breaking change in MultiJson which switched to `load`/`dump` methods. Since `load` is defined in Kernel, Ruby tries to load a file here...

I believe the MultiJson dependency in Tire is correct (`"~> 1.0"`) -- you probably had to run `bundle update`, or remove the `Gemfile.lock` and run `bundle install` again.
