### ISSUE TITLE
Updating index on ActiveRecord destroy

### ISSUE THREAD

**Issue by darrenboyd** [karmi/retire#575]
I'm seeing this error, when trying to 'destroy' an object that is indexed by Elasticsearch.

```
RuntimeError: can't modify frozen Hash
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/search.rb:202:in `[]='
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/search.rb:202:in `block in matches='
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/search.rb:200:in `instance_eval'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/search.rb:200:in `matches='
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/search.rb:149:in `block in update_index'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:403:in `_run__2777497437470779146__update_elasticsearch_index__154999634604014874__callbacks'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_update_elasticsearch_index_callbacks'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/search.rb:144:in `update_index'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.4/lib/tire/model/callbacks.rb:22:in `block in included'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:493:in `_run__2777497437470779146__destroy__154999634604014874__callbacks'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/callbacks.rb:254:in `destroy'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/transactions.rb:254:in `block in destroy'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/newrelic_rpm-3.5.4.34/lib/new_relic/agent/method_tracer.rb:493:in `block in transaction_with_trace_ActiveRecord_self_name_transaction'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/newrelic_rpm-3.5.4.34/lib/new_relic/agent/method_tracer.rb:242:in `trace_execution_scoped'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/newrelic_rpm-3.5.4.34/lib/new_relic/agent/method_tracer.rb:488:in `transaction_with_trace_ActiveRecord_self_name_transaction'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.11/lib/active_record/transactions.rb:254:in `destroy'
```

This is the stacktrace from the Rails console (object.destroy).

I've tested this in both 0.5.2 and 0.5.4 with the same result.

Thoughts?

**Comment by karmi** [comment]
Hi, I can't reliably replicate your issue:

```
>> a = Article.first
  Article Load (1.7ms)  SELECT "articles".* FROM "articles" LIMIT 1
=> #<Article id: 12714, title: "Title 1", ...>
>> a.percolate='*'
=> "*"
>> a.percolate
=> []
>> a.destroy
   (0.1ms)  begin transaction
  SQL (8.2ms)  DELETE FROM "articles" WHERE "articles"."id" = ?  [["id", 12714]]
   (16.4ms)  commit transaction
=> #<Article id: 12714, title: "Title 1", ...>
>> Article.search('title:"Title 1"').size
=> 0
```

Can you provide more information? Model settings, percolator settings, etc?

**Comment by darrenboyd** [comment]
I am no unable to reproduce this.

I'll close this now, and keep investigating.  It may be been an edge issue (maybe Rails?).
