### ISSUE TITLE
Incompatible with Rails 4 pre-release

### ISSUE THREAD

**Issue by brupm** [karmi/retire#585]
I am working on a new app which is build using rails 4 pre-release. I am running into several weird issues while trying to bootstrap Tire. 

I have added the includes to my model: 

```
class IssueGroup < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end
```

When I go into console to insert a new IssueGroup record I get the following error message:

```
NoMethodError: undefined method `_run_update_elasticsearch_index_callbacks' for #<IssueGroup:0x007fa09f5e6590>
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activemodel/lib/active_model/attribute_methods.rb:431:in `method_missing'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/attribute_methods.rb:131:in `method_missing'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/tire-0.5.4/lib/tire/model/search.rb:144:in `update_index'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/tire-0.5.4/lib/tire/model/callbacks.rb:21:in `block in included'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/callbacks.rb:358:in `block in _run__3673604901390425901__save__callbacks'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/callbacks.rb:205:in `block in _conditional_callback_around_104'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/integrations/active_record.rb:480:in `block in around_save'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:149:in `block in run_actions'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:169:in `catch_exceptions'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:147:in `run_actions'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:132:in `run_callbacks'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:211:in `run_callbacks'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:63:in `catch'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:63:in `block in perform'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/state_machine-1.1.2/lib/state_machine/transition_collection.rb:185:in `within_transaction'
... 8 levels...
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/validations.rb:57:in `save!'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/attribute_methods/dirty.rb:42:in `save!'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/transactions.rb:264:in `block in save!'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/transactions.rb:312:in `block in with_transaction_returning_status'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/transactions.rb:309:in `with_transaction_returning_status'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activerecord/lib/active_record/transactions.rb:264:in `save!'
    from (irb):15
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/railties/lib/rails/commands/console.rb:78:in `start'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/railties/lib/rails/commands/console.rb:9:in `start'
    from /Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/railties/lib/rails/commands.rb:71:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'>
```

Any help troubleshooting this is greatly appreciated. 

I have also tried setting custom `tire.mapping()` in my the model, and when I try to index using the rake task I get the following error:

```
bundle exec rake environment tire:import CLASS='Search::IssueGroup' --trace
** Invoke environment (first_time)
** Execute environment
** Invoke tire:import (first_time)
** Execute tire:import
rake aborted!
undefined method `split' for Search::IssueGroup:ActiveModel::Name
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/tire-0.5.4/lib/tire/tasks.rb:42:in `eval'
/Users/Bruno/Code/xyz/app/models/search/issue_group.rb:1:in `<top (required)>'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:422:in `load'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:422:in `block in load_file'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:614:in `new_constants_in'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:421:in `load_file'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:322:in `require_or_load'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:461:in `load_missing_constant'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/rails-0a1c61106975/activesupport/lib/active_support/dependencies.rb:182:in `const_missing'
(eval):1:in `block (2 levels) in <top (required)>'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/tire-0.5.4/lib/tire/tasks.rb:42:in `eval'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/tire-0.5.4/lib/tire/tasks.rb:42:in `block (2 levels) in <top (required)>'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:225:in `call'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:225:in `block in execute'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:222:in `each'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:222:in `execute'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:159:in `invoke_with_call_chain'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/task.rb:152:in `invoke'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:141:in `invoke_task'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:99:in `block (2 levels) in top_level'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:99:in `each'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:99:in `block in top_level'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:108:in `run_with_threads'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:93:in `top_level'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:71:in `block in run'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:158:in `standard_exception_handling'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/application.rb:68:in `run'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rake-10.0.2/bin/rake:37:in `<top (required)>'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/bin/rake:23:in `load'
/Users/Bruno/.rbenv/versions/1.9.3-p194-perf/bin/rake:23:in `<main>'
Tasks: TOP => tire:import

```

**Comment by hellvinz** [comment]
_run_update_elasticsearch_index_callbacks is not defined anymore via define_model_callback (https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L279) because of this commit rails/rails@19357a7b023fd56a5b381cd8894bb520c60cdb59

if you want to make it work, juste replace

``` ruby
instance.send :_run_update_elasticsearch_index_callbacks do
```

by

``` ruby
instance.run_callbacks :update_elasticsearch_index do
```

**Comment by romansklenar** [comment]
I was just dealing with this today, thx for solution @hellvinz !

**Comment by karmi** [comment]
Closed by 1537899, thanks!

**Comment by karmi** [comment]
@hellvinz Thanks for the suggestion!

**Comment by xpepermint** [comment]
It exists in 4.0.0.rc1.

**Comment by karmi** [comment]
@xpepermint Do you have a stacktrace or more info?

**Comment by xpepermint** [comment]
Hey @karmi 

The error says:

``` ruby
NoMethodError (undefined method `_run_update_elasticsearch_index_callbacks' for #<User:0x007f9320a82428>):
  app/controllers/users_controller.rb:30:in `block in create'
  app/controllers/users_controller.rb:29:in `create'
```

Full Trace:

``` ruby

activemodel (4.0.0.rc1) lib/active_model/attribute_methods.rb:436:in `method_missing'
activerecord (4.0.0.rc1) lib/active_record/attribute_methods.rb:131:in `method_missing'
tire (0.5.4) lib/tire/model/search.rb:144:in `update_index'
tire (0.5.4) lib/tire/model/callbacks.rb:21:in `block in included'
activesupport (4.0.0.rc1) lib/active_support/callbacks.rb:394:in `_run__3500917153409669350__save__callbacks'
activesupport (4.0.0.rc1) lib/active_support/callbacks.rb:80:in `run_callbacks'
activerecord (4.0.0.rc1) lib/active_record/callbacks.rb:299:in `create_or_update'
activerecord (4.0.0.rc1) lib/active_record/persistence.rb:103:in `save'
activerecord (4.0.0.rc1) lib/active_record/validations.rb:51:in `save'
activerecord (4.0.0.rc1) lib/active_record/attribute_methods/dirty.rb:32:in `save'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:270:in `block (2 levels) in save'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
activerecord (4.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
activerecord (4.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
activerecord (4.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:209:in `transaction'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:270:in `block in save'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
activerecord (4.0.0.rc1) lib/active_record/transactions.rb:269:in `save'
app/controllers/users_controller.rb:30:in `block in create'
actionpack (4.0.0.rc1) lib/action_controller/metal/mime_responds.rb:363:in `call'
actionpack (4.0.0.rc1) lib/action_controller/metal/mime_responds.rb:363:in `retrieve_collector_from_mimes'
actionpack (4.0.0.rc1) lib/action_controller/metal/mime_responds.rb:189:in `respond_to'
app/controllers/users_controller.rb:29:in `create'
actionpack (4.0.0.rc1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.0.rc1) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.0.rc1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.0.rc1) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.0.rc1) lib/active_support/callbacks.rb:432:in `_run__1795920866754849653__process_action__callbacks'
activesupport (4.0.0.rc1) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0.rc1) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.0.rc1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.0.rc1) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.0.rc1) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.0.rc1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.0.rc1) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.0.rc1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.0.rc1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (4.0.0.rc1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.0.rc1) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.0.rc1) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.0.rc1) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.0.rc1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.0.rc1) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.0.rc1) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.0.0.rc1) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.0.rc1) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.0.rc1) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/routing/route_set.rb:654:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.0.rc1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.0.rc1) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.0.rc1) lib/active_record/migration.rb:366:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.0.rc1) lib/active_support/callbacks.rb:392:in `_run__1125300739377227675__call__callbacks'
activesupport (4.0.0.rc1) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.0.rc1) lib/rails/rack/logger.rb:21:in `block in call'
activesupport (4.0.0.rc1) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.0.rc1) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.0.rc1) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.0.rc1) lib/rails/rack/logger.rb:21:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.0.rc1) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.0.rc1) lib/action_dispatch/middleware/static.rb:64:in `call'
railties (4.0.0.rc1) lib/rails/engine.rb:511:in `call'
railties (4.0.0.rc1) lib/rails/application.rb:96:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/Users/xpeper/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
/Users/xpeper/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
/Users/xpeper/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

Model example (i created a test app :) ):

``` ruby

class User < ActiveRecord::Base

    include Tire::Model::Search
    include Tire::Model::Callbacks

    index_name("#{Rails.env}-#{Rails.application.class.to_s.downcase}-users")

    class << self

    def create_search_index
      Tire.index(Widget.index_name) do
        create(
          :settings => {
            "analysis" => {
              "analyzer" => {
                "widget_name_analyzer" => {
                  "type"      => "custom",
                  "tokenizer" => "lowercase",
                  "filter"    => ["name_ngram"]
                }
              },
              "filter" => {
                "name_ngram" => {
                  "type"     => 'edgeNGram',
                  "min_gram" => 2,
                  "max_gram" => 7,
                  "side"     => "front"
                }
              }
            }
          },
          :mappings => {
            :show => {
              :properties => {
                :id         => { :type => :integer                                     },
                :full_name  => { :type => :string,  :analyzer => :widget_name_analyzer },
                :email          => { :type => :string,  :analyzer => :widget_name_analyzer }
              }
            }
          }        
        )
      end
    end

    def delete_search_index
      search_index.delete
    end

    def search_index
      Tire.index(Widget.index_name)
    end

  end 

end

```

I hope it helps.

**Comment by hellvinz** [comment]
from the stack trace it seems that you are running tire 0.5.4, the fix has been merged in 0.5.5
regards

**Comment by karmi** [comment]
@hellvinz Yes, thanks!, @xpepermint check out 1537899

**Comment by xpepermint** [comment]
I must have been editing the wrong Gemfile :). Thx! 0.5.8 works...
