### ISSUE TITLE
Batch import without Tire::Model::Search & Tire::Model::Callbacks

### ISSUE THREAD

**Issue by reiz** [karmi/retire#587]
I saw in the documentation That I can do a batch import like this: "Article.import". But how can I do a batch import if my model does not include this: 

include Tire::Model::Search
include Tire::Model::Callbacks

I mean if the modell is decoupled from Tire. I tried something like this: 

Tire.index( Settings.elasticsearch_product_index ).import Product

But that doesn't work.
I appreciate every hint. 
Many Thanks.

**Comment by karmi** [comment]
Hi, any new information on this? The `MyModel.import` is model only -- use `Tire.index('myindex').bulk_store <AN ARRAY OF DOCUMENTS>`.

**Comment by reiz** [comment]
I just tried the bulk_store with the newest version 0.5.4. But I am getting always json parsing exceptions. 

``` java
[2013-02-13 13:06:54,007][DEBUG][action.bulk              ] [Schultz, Herman] [product][2] failed to execute bulk item (index) index {[product][document][4f04d600e4b0c514865d01a9], source[{:_id=>"4f04d600e4b0c514865d01a9", :_type=>"product", :name=>"util-plan-fetcher-impl", :description=>"Implementation for the resource fetchers - bundle version", :description_manual=>"", :language=>"Java", :followers=>0, :group_id=>"org.ow2.bundles", :prod_key=>"org.ow2.bundles/util-plan-fetcher-impl", :prod_type=>"Maven2"}]}
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse
  at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:501)
  at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:430)
  at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:318)
  at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:157)
  at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:533)
  at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:431)
  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
  at java.lang.Thread.run(Thread.java:680)
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Unexpected character (':' (code 58)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name
 at [Source: [B@106f29c8; line: 1, column: 125423]
  at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1378)
  at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:599)
  at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:520)
  at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._handleUnusualFieldName(UTF8StreamJsonParser.java:1728)
  at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._parseFieldName(UTF8StreamJsonParser.java:1409)
  at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:677)
  at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:48)
  at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:460)
  ... 8 more
```

If I index each element one by one, it works fine. But with the bulk_store it doesn't work. 
This here is my bulk code: 

``` Ruby
products = Product.all().skip( skip ).limit( bulk )
Tire.index( Settings.elasticsearch_product_index ).bulk_store products.to_a
```

**Comment by reiz** [comment]
By the way, bulk is 100. I am always fetching 100 documents from MongoDB and want to index them.

**Comment by karmi** [comment]
@reiz You have to provide more information, example of how the model is serialized, etc. Or catch me on IRC.

**Comment by reiz** [comment]
@karmi OK. What else you need? But I am not doing anything special. I basically fetching 100 documents from MongoDB and that's it. 

Where can I find you on IRC ?

**Comment by karmi** [comment]
Closing this, please reopen with more info if the issue persists.
