### ISSUE TITLE
Wrong model inflection causes Uninitialized Constant

### ISSUE THREAD

**Issue by alantriesagain** [karmi/retire#733]
When I try to import all models (and tire walks through the entire app/models folder), it throws an error when trying to "classify" the "address" model name, which is already singular, and classify attempts to singularize it.

```
rake tire:import:all FORCE=true --trace
(in /Users/alanmeira/development/engarte)
** Invoke tire:import:all (first_time)
** Execute tire:import:all
[IMPORT] Rails detected, loading environment...
** Invoke environment (first_time)
** Execute environment
[IMPORT] Loading models from: /Users/alanmeira/development/engarte/app/models
rake aborted!
uninitialized constant Addres
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:230:in `block in constantize'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `each'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `constantize'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/tire-0.5.7/lib/tire/tasks.rb:139:in `block (4 levels) in <top (required)>'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/tire-0.5.7/lib/tire/tasks.rb:135:in `each'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/gems/tire-0.5.7/lib/tire/tasks.rb:135:in `block (3 levels) in <top (required)>'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/alanmeira/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392@global/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/bin/rake:19:in `load'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/bin/rake:19:in `<main>'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
/Users/alanmeira/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => tire:import:all
```

**Comment by karmi** [comment]
Hi, `Addres` is not a singular form of adress, it's incorrect English syntax. Rename your model to `Address` (plural: addresses) and it should work.

**Comment by alantriesagain** [comment]
The model is already address, Karel. This is exactly the point. Tire tries
to singularize address using classify, and it returns addres.
To fix it, I added on inflections that the "singular" of address is address
too.

inflect.singular 'address', 'address'

On Sun, May 19, 2013 at 3:35 AM, Karel Minarik notifications@github.comwrote:

> Hi, Addres is not a singular form of adress, it's incorrect English
> syntax. Rename your model to Adress (plural: adresses) and it should work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/karmi/tire/issues/733#issuecomment-18113157
> .

## 

Atenciosamente,

Alan Carlos Meira Leal
http://www.linkedin.com/in/alanmeira | (31) 9788-2008 | Skype: alanmeira

**Comment by karmi** [comment]
I'm sorry, I see your point:

```
>> 'post'.classify
=> "Post"
>> 'address'.classify
=> "Addres"
```

I think the way to solve it would be to simply `pluralize` the file name, since [classify](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-classify) explicitely says "create[s] a class name from a plural table name". I'll try to have a look into it soon.

(Note that you can import the individual model with `rake tire:import:model CLASS='Address'`.)

**Comment by karmi** [comment]
@alanmeira Sorry it took so long, should be fixed now.
