### ISSUE TITLE
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2)

### ISSUE THREAD

**Issue by TheHodge** [karmi/retire#781]
I'm currently using Tire with Sidekiq, I'm doing some quite write heavy things with Tire Persistance and things work fine for a few minutes but then I get 

```
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2)
```

With a stacktrace of 

``` trace
/usr/lib/ruby/1.9.1/net/http.rb:763:in `initialize'
/usr/lib/ruby/1.9.1/net/http.rb:763:in `open'
/usr/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
/usr/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
/usr/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
/usr/lib/ruby/1.9.1/net/http.rb:763:in `connect'
/usr/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
/usr/lib/ruby/1.9.1/net/http.rb:745:in `start'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/tire-0.6.0/lib/tire/http/client.rb:11:in `get'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/tire-0.6.0/lib/tire/index.rb:331:in `retrieve'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/tire-0.6.0/lib/tire/model/persistence/finders.rb:26:in `find'
/home/rails/domainapi/releases/20130702172920/app/workers/update_all_data_worker.rb:9:in `perform'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:109:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:109:in `block in invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-failures-0.1.0/lib/sidekiq/failures/middleware.rb:8:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/server/timeout.rb:14:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/server/retry_jobs.rb:50:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:111:in `block in invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:114:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/middleware/chain.rb:114:in `invoke'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/processor.rb:87:in `stats'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/sidekiq-2.9.0/lib/sidekiq/processor.rb:47:in `block in process'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `public_send'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `dispatch'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb:18:in `block in initialize'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call'
/home/rails/domainapi/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create'
```

From the outset it looks like a timeout error, however my elasticsearch server isn't reporting any sort of issues (it's on a dedicated box with 20+gig of ram).

Locally I am running a lot of curl connections, however I've compiled curl with c-ares which has stopped any timeouts related to that issue.

**Comment by karmi** [comment]
RestClient doesn't have HTTP keepalive, and ES could simply refuse to serve many connections -- can you try with the Curb client? (Grep the repo for "curb")

**Comment by mereghost** [comment]
I had this problem occur to us and it boiled down to the OS getting all its
dynamic ports assigned.

**Comment by TheHodge** [comment]
@karmi your curb suggestions seem to have fixed it so far.. will report back if it appears again
