### ISSUE TITLE
No such file or directory - getaddrinfo

### ISSUE THREAD

**Issue by voxxit** [karmi/retire#787]
Getting a strange error on Ubuntu 13.04 & Ruby 2.0.0-p247 (and -p145) with the tire gem when running my rspec code:

```
/home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': No such file or directory - getaddrinfo (Errno::ENOENT)
        from /home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
        from /home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
        from /home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from /home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
        from /home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from /home/philo/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/rest-client-1.6.7/lib/restclient.rb:88:in `head'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/tire-0.6.0/lib/tire/http/client.rb:43:in `head'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/tire-0.6.0/lib/tire/index.rb:18:in `exists?'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/tire-0.6.0/lib/tire/model/indexing.rb:107:in `create_elasticsearch_index'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/tire-0.6.0/lib/tire/model/indexing.rb:61:in `mapping'
        from /home/philo/.rvm/gems/ruby-2.0.0-p247/gems/tire-0.6.0/lib/tire/model/search.rb:298:in `mapping'
```

Not sure why, but this works on my Mac, but not on Ubuntu.

**Comment by bradgriffin** [comment]
I have also been having this problem. It seems to be isolated to when I run within tmux. Are you using tmux by any chance?

**Comment by karmi** [comment]
Found this thread, could it somehow be related https://bugzilla.redhat.com/show_bug.cgi?id=956035? Can you run the Tire integration test suite on the system?

**Comment by karmi** [comment]
@voxxit Can you please run Tire integration tests (or their part) on the system?

---

For reference:

``` shell
$ ruby -v
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin12.2.0]

$ ruby -I lib:test test/integration/active_record_searchable_test.rb 
...
Finished in 86.083343 seconds.
```
