### ISSUE TITLE
Tire overrides "Array.index" on AR collections, model properties named "index"

### ISSUE THREAD

**Issue by hbrock25** [karmi/retire#790]
I have code which relies on articles.index(article) returning the position of a given article in the array. Adding   

include Tire::Model::Search
include Tire::Model::Callbacks

to article.rb breaks this code, b/c article (and a collection of articles as well) now has a method "index" that returns the index object for the article.

Is there a way to namespace the index method or otherwise keep it from trampling the native Ruby version?

This is tire (0.6.0) on Rails 3.1.2/ruby 1.9.3

Apols if I'm overlooking something obvious here...

**Comment by karmi** [comment]
Please see the 'tire' proxy in the Readme, Tire doesn't overload any already defined methods.

**Comment by hbrock25** [comment]
Hmm... what about instance properties? I also have an object with an index field defined ("foo.index" gives a specific position of foo in a list of foos) and it appears to be overriding that as well. Do I simply need to explicitly define the property in the model?

(Thanks for the quick response BTW)

**Comment by karmi** [comment]
Tire shouldn't overload any defined methods, see the source, could you post relevant parts of your models?

**Comment by hbrock25** [comment]
Sure...

So I have a table like this:

```
class AddColumnsToArticles < ActiveRecord::Migration
  def up
    add_column(:articles, :subhead, :string)
    add_column(:articles, :index, :integer, :null => false)
  end
```

It backs a model like this:

```
class Article < ActiveRecord::Base

  include Tire::Model::Search
  include Tire::Model::Callbacks
...
  def up
    before = Article.where("issue_id = ?", self.issue.id)
      .where("index < ?", self.index)
      .order("index DESC").first
    if before.present?
      self.index, before.index = before.index, self.index
      before.save
      save
    end
  end
```

Calling "up" from my tests now yields this error:

```
  1) Article should create a valid article
     Failure/Error: @article1 = FactoryGirl.create :article, :issue_id => @issue1.id
     NoMethodError:
       undefined method `>' for #<Tire::Index:0x0000000c47d248 @name="articles">
     # ./app/models/article.rb:71:in `set_index_if_null'
     # ./spec/models/article_spec.rb:6:in `block (2 levels) in <top (required)>'
```

You can see that article.index now returns a Tire::Index, rather than the integer defined in the database.

To be clear, I don't have an "index" method defined anywhere in the model -- it's of course implied by the database table.

--Hugh

**Comment by karmi** [comment]
Strange, ActiveRecord attributes should be defined as regular methods; will investigate it further later.

**Comment by karmi** [comment]
Been digging a bit into this, and seems like ActiveRecord is using some [`module_eval`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/read.rb), which might throw Tire off, when it [looks for the method being already defined](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L297).

I can replicate the issue just in console when the model has a method named `index`:

``` ruby
# Migration
...
add_column(:articles, :index, :integer)
...

# Console:
a = Article.create title: 'With index', index: 123
>> a.index
=> #<Tire::Index:0x007f9d564018e8 @name="articles">
# BUT SHOULD BE `123`
```

The workaround for now would be to use the `read_attribute` accessor:

``` ruby
>> a.read_attribute(:index)
=> 2
>> a[:index]
=> 2
```

**Comment by vdh** [comment]
I had this problem occur for AR collections, and my workaround was to replace `index` with `find_index`, since [the docs for Array says that index is an alias of find_index](http://www.ruby-doc.org/core-2.0.0/Array.html#method-i-index).
