### ISSUE TITLE
Disable Tire on Rails - development & test (?)

### ISSUE THREAD

**Issue by flockonus** [karmi/retire#801]
Hi,

I've been using Tire with Rails and Mongoid, it seems to work quite well.

I would like it not to run on development and test though, so I don't have to increase the complexity of the stack.

Another way to put it, is that I would only like it to run on production.

my model simplified is:

``` ruby
class Wine
  include Mongoid::Document
  include Tire::Model::Search
  include Tire::Model::Callbacks

  settings :number_of_shards => 2

  mapping do
     # should not search this, maybe all I have to do is not index -_-
     indexes :style,   store: "no" #index: :not_analyzed
     # indexes :vintage #, type: 'integer' (don't 'type' it, unless can guarantee it is always integer|null)
     indexes :designation
     indexes :winery
  end

  self.include_root_in_json = false
  def to_indexed_json
    reduced_info = {
      id: _id.to_s,
      vintage: year,
    }
    reduced_info.to_json
  end

end
```

Becasue when running `@wine.save` I get this on development with no Elasticsearch server running: 

```
Errno::ECONNREFUSED - Connection refused - connect(2):
  /Users/flockonus/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
  /Users/flockonus/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
  /Users/flockonus/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
  /Users/flockonus/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `connect'
  /Users/flockonus/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
  /Users/flockonus/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:744:in `start'
  rest-client (1.6.7) lib/restclient/request.rb:172:in `transmit'
  rest-client (1.6.7) lib/restclient/request.rb:64:in `execute'
  rest-client (1.6.7) lib/restclient/request.rb:33:in `execute'
  rest-client (1.6.7) lib/restclient.rb:72:in `post'
  tire (0.6.0) lib/tire/http/client.rb:19:in `post'
  tire (0.6.0) lib/tire/index.rb:146:in `store'
  tire (0.6.0) lib/tire/model/search.rb:148:in `block in update_index'
  activesupport (3.2.13) lib/active_support/callbacks.rb:403:in `_run__1929314581131167503__update_elasticsearch_index__4157636883922693572__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_update_elasticsearch_index_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (3.1.4) lib/mongoid/callbacks.rb:130:in `run_callbacks'
  tire (0.6.0) lib/tire/model/search.rb:144:in `update_index'
  tire (0.6.0) lib/tire/model/callbacks.rb:21:in `block in included'
  activesupport (3.2.13) lib/active_support/callbacks.rb:431:in `_run__1929314581131167503__save__4157636883922693572__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (3.1.4) lib/mongoid/callbacks.rb:130:in `run_callbacks'
  mongoid (3.1.4) lib/mongoid/persistence/modification.rb:24:in `prepare'
  mongoid (3.1.4) lib/mongoid/persistence/operations/update.rb:45:in `persist'
  mongoid (3.1.4) lib/mongoid/persistence.rb:145:in `update'
  mongoid (3.1.4) lib/mongoid/persistence.rb:82:in `save'
  app/controllers/admin/wines_controller.rb:133:in `block in update'
  actionpack (3.2.13) lib/action_controller/metal/mime_responds.rb:270:in `retrieve_collector_from_mimes'
  actionpack (3.2.13) lib/action_controller/metal/mime_responds.rb:194:in `respond_to'
  app/controllers/admin/wines_controller.rb:132:in `update'
  actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.13) lib/active_support/callbacks.rb:447:in `_run__2058257382087028680__process_action__1158254299624417706__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in `call'
  mongoid (3.1.4) lib/rack/mongoid/middleware/identity_map.rb:34:in `block in call'
  mongoid (3.1.4) lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
  mongoid (3.1.4) lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
  warden (1.2.1) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__2896109155536503160__call__4157636883922693572__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/deflater.rb:13:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.13) lib/rails/rack/log_tailer.rb:17:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.5) lib/rack/server.rb:268:in `start'
  railties (3.2.13) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.13) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.13) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `<main>'
```

**Comment by karmi** [comment]
I'm not sure it's a good idea, and Elasticsearch is pretty easy to install -- see the Rails app template, which effectively does it within a `rails new` command.

That said, you just have to intercept the calls to ES in these environments -- that is, when Tire is checking for index existence in `mapping`, and then when saving records. The Readme has some good info about how to handle the callbacks manually...

**Comment by flockonus** [comment]
I understand your concern, our use-case is pretty different than usual since our Rails just populate E.S. and the whole interaction happen via an API.

Seeing here, is amazingly simple =)

```
  COMMAND = <<-COMMAND.gsub(/^    /, '')
    curl -k -L -# -o elasticsearch-0.20.6.tar.gz \
      "http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.20.6.tar.gz"
    tar -zxf elasticsearch-0.20.6.tar.gz
    rm  -f   elasticsearch-0.20.6.tar.gz
    ./elasticsearch-0.20.6/bin/elasticsearch -p #{destination_root}/tmp/pids/elasticsearch.pid
  COMMAND
```

Still think that should be an `.off()` somewhere, so I am forking and will try coming with an answer =)

Maybe as a separate note, could the HTTP calls happen async? As a fire and forget? In that case I wouldn't have to worry if it failed in development / test.
I see you have Faraday, don't they enable that?

Even if not for my particular problem, I guess implementing an async handler could benefit a performance for those who don't use e.s. as DB; example: http://stackoverflow.com/a/11373486/250019

**Comment by flockonus** [comment]
My pull request is very naive and integration tests failed :P
I guess it is because we don't have visibility of Tire instance inside RestClient (?)

Overall idea is not to change anything on how the lib works, except that when it is about to perform the HTTP, it doesn't and just return a mock object.

**Comment by karmi** [comment]
@flockonus I still don't understand correctly why disabling the network interaction would be helpful in test or development, but would like to help you with your problem.

First, the `off!` idea is nice, but it only applies to the default RestClient based client, would require mode code scattered across the clients ets. This is clearly a lack of proper architecture on Tire's part, not your code, but still, the result won't be pretty.

Second, even a messy architecture like Tire's has a clean way how to achieve what you want:
1. Subclass a specific Tire HTTP Client (default, Curb, Faraday, etc), and "mock" the HTTP communication (isolated in `perform` or `request` method)
2. Use this client in the specific environment, like this: 

``` ruby
require 'my-mock-client'
Tire.configure do
    client Rails.env.production? ? Tire::HTTP::Client::Curb : MyMockClient
end
```

Does it make sense?

**Comment by flockonus** [comment]
Thanks a lot for the consideration on this issue, @karmi 

About the motivation on why, it might be a particular case, but the underlying reasoning is that I trust Elasticsearch server, and Tire, so there is no reason to burden the team with one more dependency, since this server don't query. I'd like to know if you have considerations on it =)

The mock client idea is _awesome_! I will try this as soon as I have some time and updates here, thanks =)

**Comment by karmi** [comment]
@flockonus I understand the motivation to keep the stack for developers slim. On the other hand, when your project grows, you'll need to setup additional technologies/services. Elasticsearch is very easy to install, compared to many other technologies, but you might want to research [Vagrant](http://www.vagrantup.com) to provide your developers with an environment matching the production.

Closing this issue, if that's OK.
