### ISSUE TITLE
index_name is correct, but index is wrong with mongoid 3 

### ISSUE THREAD

**Issue by lazing** [karmi/retire#909]
it breaks the index create

see following

``` ruby
irb(main):007:0> Product.index_name
=> "products"

irb(main):011:0> Product.tire.create_elasticsearch_index
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":"InvalidIndexNameException[[Product] Invalid index name [Product], must be lowercase]","status":400}


irb(main):002:0> Product.tire.index
=> #<Tire::Index:0x00000008dc95a8 @name=Product>

irb(main):012:0> Product.index
ArgumentError: wrong number of arguments (0 for 1)
    from /home/ryan/.rvm/gems/ruby-1.9.3-p392/gems/mongoid-3.0.23/lib/mongoid/indexes.rb:79:in `index'
    from (irb):12
    from /home/ryan/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/commands/console.rb:47:in `start'
    from /home/ryan/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/commands/console.rb:8:in `start'
    from /home/ryan/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by karmi** [comment]
So, `index` is reserved in Mongoid. You should use the `tire` proxy. I can't replicate the issue:

``` ruby
% rails console
Loading development environment (Rails 3.2.15)

>> Mongoid::VERSION
=> "3.1.5"

>> Article.tire.index_name
=> "articles"

>> Article.tire.index.delete
=> true
>> Article.tire.create_elasticsearch_index
=> nil

>> Article.tire.index.mapping
=> {"article"=>{"properties"=>{"title"=>{"type"=>"string", "analyzer"=>"snowball"}}}}
```

**Comment by lazing** [comment]
@karmi i have found a solution

add following to model

``` ruby
tire do
  index_name {"products"}   # WORKS!
end
```

the code from `retire/lib/tire/model/ search.rb:118`

``` ruby
        # Returns a Tire::Index instance for this model.
        #
        # Example usage: `Article.index.refresh`.
        #
        def index
          name = index_name.respond_to?(:to_proc) ? klass.instance_eval(&index_name) : index_name
          @index = Index.new(name)
        end
```

`index_name.respond_to?(:to_proc)` always return _true_

I am not sure the issue should be fixed, may add some document?

UPDATE:

```
irb(main):001:0> Mongoid::VERSION
=> "3.0.23"
```

**Comment by karmi** [comment]
It should work out of the box. I can't replicate the issue on Mongoid 3.1.5.

**Comment by lazing** [comment]
thanks all the same. since there is a solution, will close it.
